apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8srequiredlabels
  annotations:
    description: >-
      Requires resources to contain specified labels, with values matching
      provided regular expressions.
spec:
  crd:
    spec:
      names:
        kind: K8sRequiredLabels
      validation:
        openAPIV3Schema:
          type: object
          properties:
            message:
              type: string
            labels:
              type: array
              description: >-
                A list of labels and values the object must specify.
              items:
                type: object
                properties:
                  key:
                    type: string
                    description: >-
                      The required label.
                  allowedRegex:
                    type: string
                    description: >-
                      If specified, a regular expression the annotation's value
                      must match. The value must contain at least one match for
                      the regular expression.
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8srequiredlabels

        get_message(parameters, _default) = msg {
          not parameters.message
          msg := _default
        }

        get_message(parameters, _default) = msg {
          msg := parameters.message
        }

        violation[{"msg": msg, "details": {"missing_labels": missing}}] {
          provided := {label | input.review.object.metadata.labels[label]}
          required := {label | label := input.parameters.labels[_].key}
          missing := required - provided
          count(missing) > 0
          def_msg := sprintf("you must provide labels: %v", [missing])
          msg := get_message(input.parameters, def_msg)
        }

        violation[{"msg": msg}] {
          value := input.review.object.metadata.labels[key]
          expected := input.parameters.labels[_]
          expected.key == key
          # do not match if allowedRegex is not defined, or is an empty string
          expected.allowedRegex != ""
          not re_match(expected.allowedRegex, value)
          def_msg := sprintf("Label <%v: %v> does not satisfy allowed regex: %v", [key, value, expected.allowedRegex])  
          msg := get_message(input.parameters, def_msg)  
        }  
          
        # Additional logic to validate the usage-id against the namespace name  
        violation[{"msg": msg}] {  
          ns_name := input.review.object.metadata.name  
          label_value := input.review.object.metadata.labels["usage-id"]  
          # Extract the usage-id from the namespace name using a regex pattern  
          # that matches the allowedRegex pattern for usage-id from the beginning of the name  
          re_match(`^(aa|bb|pp)[0-9]{8}.*$`, ns_name)  
          # Grab the usage-id part from the namespace name using a custom function  
          ns_usage_id := extract_usage_id(ns_name)  
          # Check if the usage-id label matches the extracted usage-id from the namespace name  
          not label_value == ns_usage_id  
          def_msg := sprintf("The usage-id label <%v> does not match the usage-id <%v> from the namespace name", [label_value, ns_usage_id])  
          msg := get_message(input.parameters, def_msg)  
        }  

        # Custom function to extract usage-id from the namespace name
        extract_usage_id(ns_name) = usage_id {
          usage_id := substring(ns_name, 0, 10)
        }
